### ISSUE TITLE
拜年祭类特殊类别内容（未使用专题页链接）无法正确获取 av 号并下载

### ISSUE THREAD

**Issue by imgradeone** [nilaoda/BBDown#740]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
BBDown 1.6.1 (dotnet tool) 

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Windows 11 22H2 (Build 22621.2283)

#### 3. 你使用的完整命令是什么？
```sh
#灯火【2022拜年纪单品】
bbdown https://www.bilibili.com/video/BV11Y411t7k5
```
#### 4. 遇到了什么问题？
相应视频获取到的 av 号为 `ep:`，导致无法获取数据（`The given key was not present in the dictionary.`）

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
（不便提供截图，转为多行命令日志并隐藏部分我认为不适宜展示的信息）

```sh
PS D:\Archive> bbdown https://www.bilibili.com/video/BV11Y411t7k5 --debug
BBDown version 1.6.1, Bilibili Downloader.
遇到问题请首先到以下地址查阅有无相关信息：
https://github.com/nilaoda/BBDown/issues

[2023-10-13 15:33:07.603] - 获取网页重定向地址: Url: https://github.com/nilaoda/BBDown/releases/latest, Headers: User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) Gecko/20100101 Firefox/92.548
Accept-Encoding: gzip, deflate
Cache-Control: no-cache
[2023-10-13 15:33:07.855] - AppDirectory: C:\Users\imgradeone\.dotnet\tools
[2023-10-13 15:33:07.925] - 运行参数：{"Url":"https://www.bilibili.com/video/BV11Y411t7k5","UseTvApi":false,"UseAppApi":false,"UseIntlApi":false,"UseMP4box":false,"EncodingPriority":null,"DfnPriority":null,"OnlyShowInfo":false,"ShowAll":false,"UseAria2c":false,"Interactive":false,"HideStreams":false,"MultiThread":true,"VideoOnly":false,"AudioOnly":false,"DanmakuOnly":false,"CoverOnly":false,"SubOnly":false,"Debug":true,"SkipMux":false,"SkipSubtitle":false,"SkipCover":false,"ForceHttp":true,"DownloadDanmaku":false,"SkipAi":true,"VideoAscending":false,"AudioAscending":false,"AllowPcdn":false,"ForceReplaceHost":true,"FilePattern":"","MultiFilePattern":"","SelectPage":"","Language":"","UserAgent":"","Cookie":"","AccessToken":"","Aria2cArgs":"","WorkDir":"","FFmpegPath":"","Mp4boxPath":"","Aria2cPath":"","UposHost":"","DelayPerPage":"0","Host":"api.bilibili.com","EpHost":"api.bilibili.com","Area":"","ConfigFile":null,"Aria2cProxy":"","OnlyHevc":false,"OnlyAvc":false,"OnlyAv1":false,"AddDfnSubfix":false,"NoPaddingPageNum":false,"BandwithAscending":false}
[2023-10-13 15:33:07.927] - 加载本地cookie...
[2023-10-13 15:33:07.927] - 文件路径：C:\Users\imgradeone\.dotnet\tools\BBDown.data
[2023-10-13 15:33:07.934] - 获取网页内容: Url: https://api.bilibili.com/x/web-interface/nav, Headers: User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) Gecko/20100101 Firefox/92.548
Accept-Encoding: gzip, deflate
Cookie: DedeUserID=107483999;DedeUserID__ckMd5=***************;Expires=**************;SESSDATA=***********************;bili_jct=**********************;gourl=https%253A%252F%252Fwww.bilibili.com%252F
Referer: https://www.bilibili.com/
Cache-Control: no-cache
[2023-10-13 15:33:08.513] - Response: {"code":0,"message":"0","ttl":1,"data":{"isLogin":true,"email_verified":1,"face":"https://i2.hdslb.com/bfs/face/16bca05206350a3af78ad5839b4467c985903486.jpg","face_nft":0,"face_nft_type":0,"level_info":{"current_level":6,"current_min":28800,"current_exp":**********,"next_exp":"--"},"mid":107483999,"mobile_verified":1,"money":******,"moral":70,"official":{"role":0,"title":"","desc":"","type":-1},"officialVerify":{"type":-1,"desc":""},"pendant":{"pid":0,"name":"","image":"","expire":0,"image_enhance":"","image_enhance_frame":""},"scores":0,"uname":"自言者一么","vipDueDate":1944144000000,"vipStatus":1,"vipType":2,"vip_pay_type":0,"vip_theme_type":0,"vip_label":{"path":"","text":"十年大会员","label_theme":"ten_annual_vip","text_color":"#FFFFFF","bg_style":1,"bg_color":"#FB7299","border_color":"","use_img_label":true,"img_label_uri_hans":"https://i0.hdslb.com/bfs/activity-plat/static/20220608/e369244d0b14644f5e1a06431e22a4d5/wltavwHAkL.gif","img_label_uri_hant":"","img_label_uri_hans_static":"https://i0.hdslb.com/bfs/vip/802418ff03911645648b63aa193ba67997b5a0bc.png","img_label_uri_hant_static":"https://i0.hdslb.com/bfs/activity-plat/static/20220614/e369244d0b14644f5e1a06431e22a4d5/8u7iRTPE7N.png"},"vip_avatar_subscript":1,"vip_nickname_color":"#FB7299","vip":{"type":2,"status":1,"due_date":******************,"vip_pay_type":0,"theme_type":0,"label":{"path":"","text":"十年大会员","label_theme":"ten_annual_vip","text_color":"#FFFFFF","bg_style":1,"bg_color":"#FB7299","border_color":"","use_img_label":true,"img_label_uri_hans":"https://i0.hdslb.com/bfs/activity-plat/static/20220608/e369244d0b14644f5e1a06431e22a4d5/wltavwHAkL.gif","img_label_uri_hant":"","img_label_uri_hans_static":"https://i0.hdslb.com/bfs/vip/802418ff03911645648b63aa193ba67997b5a0bc.png","img_label_uri_hant_static":"https://i0.hdslb.com/bfs/activity-plat/static/20220614/e369244d0b14644f5e1a06431e22a4d5/8u7iRTPE7N.png"},"avatar_subscript":1,"nickname_color":"#FB7299","role":7,"avatar_subscript_url":"","tv_vip_status":1,"tv_vip_pay_type":0,"tv_due_date":**************},"wallet":{"mid":107483999,"bcoin_balance":****,"coupon_balance":*****,"coupon_due_time":0},"has_shop":true,"shop_url":"https://gf.bilibili.com?msource=main_station","allowance_count":0,"answer_status":0,"is_senior_member":1,"wbi_img":{"img_url":"https://i0.hdslb.com/bfs/wbi/7cd084941338484aae1ad9425b84077c.png","sub_url":"https://i0.hdslb.com/bfs/wbi/4932caff0ff746eab6f01bf08b70ac45.png"},"is_jury":false}}
[2023-10-13 15:33:08.552] - wbi: ********************************
[2023-10-13 15:33:08.552] - 检测账号登录...
[2023-10-13 15:33:08.552] - 获取aid...
[2023-10-13 15:33:08.563] - 获取网页重定向地址: Url: https://www.bilibili.com/video/av253699099/, Headers: User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) Gecko/20100101 Firefox/92.548
Accept-Encoding: gzip, deflate
Cache-Control: no-cache
[2023-10-13 15:33:08.977] - Location: https://github.com/nilaoda/BBDown/releases/tag/1.6.1
[2023-10-13 15:33:09.014] - Location: https://www.bilibili.com/festival/2022bnj?bvid=BV11Y411t7k5&
[2023-10-13 15:33:09.015] - 获取aid结束: ep:
[2023-10-13 15:33:09.016] - 获取视频信息...
[2023-10-13 15:33:09.019] - 获取网页内容: Url: https://api.bilibili.com/pgc/view/web/season?ep_id=, Headers: User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) Gecko/20100101 Firefox/92.548
Accept-Encoding: gzip, deflate
Cookie: DedeUserID=107483999;DedeUserID__ckMd5=***************;Expires=**************;SESSDATA=***********************;bili_jct=**********************;gourl=https%253A%252F%252Fwww.bilibili.com%252F
Referer: https://www.bilibili.com/
Cache-Control: no-cache
[2023-10-13 15:33:09.170] - Response: {"code":-404,"message":"啥都木有"}
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Text.Json.JsonElement.GetProperty(String propertyName)
   at BBDown.Core.Fetcher.BangumiInfoFetcher.FetchAsync(String id) in D:\VSProjects\【解析】\BBDown\BBDown.Core\Fetcher\BangumiInfoFetcher.cs:line 17
   at BBDown.Program.DoWorkAsync(MyOption myOption) in D:\VSProjects\【解析】\BBDown\BBDown\Program.cs:line 443
```

**Comment by imgradeone** [comment]
Duplicated #735
